Spring:
  datasource:
    schema: schema.sql
    data: data.sql
    initialization-mode: always
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
