CREATE TABLE IF NOT EXISTS books (
	id BIGINT NOT NULL CONSTRAINT book_pk	PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	author_id BIGINT CONSTRAINT book_author_id_fk REFERENCES authors ON DELETE SET NULL,
	genre_id BIGINT CONSTRAINT book_genre_id_fk REFERENCES genres	ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS authors (
	id BIGINT NOT NULL CONSTRAINT author_pk PRIMARY KEY,
	first_name VARCHAR(100) NOT NULL,
	middle_name VARCHAR(100),
	last_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
	id BIGINT NOT NULL CONSTRAINT genre_pk PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS genre_name_uindex ON genres (name);

